database:
  name: "${DB_NAME}"
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"

jwt:
  secret: "${JWT_SECRET}"
  expiration: "${JWT_EXPIRATION}"

redis:
  host: "${REDIS_HOST}"
  port: "${REDIS_PORT}"
  password: "${REDIS_PASSWORD}"

app:
  host: "${APP_HOST}"
  port: "${APP_PORT}"
  debug: "${DEBUG_APP}"
